using Onyx.CodeGen.Core.Math;

namespace Onyx.CodeGen.ComponentDSL
{
    public static class DSLTypes
    {
        public static readonly Dictionary<string, Type> ONYX_TYPE_TO_DSL_TYPE = new Dictionary<string, Type>()
        {
            { "onyxU8", typeof(byte) },
            { "onyxU16", typeof(UInt16) },
            { "onyxU32", typeof(UInt32) },
            { "onyxU64", typeof(UInt64) },
            { "onyxU128", typeof(UInt128) },
            { "onyxS8", typeof(sbyte) },
            { "onyxS16", typeof(Int16) },
            { "onyxS32", typeof(Int32) },
            { "onyxS64", typeof(Int64) },
            { "onyxS128", typeof(Int128) },
            { "onyxF32", typeof(float) },
            { "onyxF64", typeof(double) },
            { "Vector2u8", typeof(Vector2<byte>) },
            { "Vector2u16", typeof(Vector2<UInt16>) },
            { "Vector2u32", typeof(Vector2<UInt32>) },
            { "Vector2u64", typeof(Vector2<UInt64>) },
            { "Vector2s8", typeof(Vector2<sbyte>) },
            { "Vector2s16", typeof(Vector2<Int16>) },
            { "Vector2s32", typeof(Vector2<Int32>) },
            { "Vector2s64", typeof(Vector2<Int64>) },
            { "Vector2f32", typeof(Vector2<float>) },
            { "Vector2f64", typeof(Vector2<double>) },
            { "Vector3f64", typeof(Vector3<byte>) },
            { "Vector3f64", typeof(Vector3<UInt16>) },
            { "Vector3f64", typeof(Vector3<UInt32>) },
            { "Vector3f64", typeof(Vector3<UInt64>) },
            { "Vector3f64", typeof(Vector3<sbyte>) },
            { "Vector3f64", typeof(Vector3<Int16>) },
            { "Vector3f64", typeof(Vector3<Int32>) },
            { "Vector3f64", typeof(Vector3<Int64>) },
            { "Vector3f64", typeof(Vector3<float>) },
            { "Vector3f64", typeof(Vector3<double>) },
            { "Vector4f64", typeof(Vector4<byte>) },
            { "Vector4f64", typeof(Vector4<UInt16>) },
            { "Vector4f64", typeof(Vector4<UInt32>) },
            { "Vector4f64", typeof(Vector4<UInt64>) },
            { "Vector4f64", typeof(Vector4<sbyte>) },
            { "Vector4f64", typeof(Vector4<Int16>) },
            { "Vector4f64", typeof(Vector4<Int32>) },
            { "Vector4f64", typeof(Vector4<Int64>) },
            { "Vector4f64", typeof(Vector4<float>) },
            { "Vector4f64", typeof(Vector4<double>) },
            { "String", typeof(string) }
        };

        public static readonly Type[] NUMERICAL_TYPES = {

            typeof(byte),
            typeof(UInt16),
            typeof(UInt32),
            typeof(UInt64),
            typeof(UInt128),
            typeof(sbyte),
            typeof(Int16),
            typeof(Int32),
            typeof(Int64),
            typeof(Int128),
            typeof(float),
            typeof(double),
            typeof(Vector2<byte>),
            typeof(Vector2<UInt16>),
            typeof(Vector2<UInt32>),
            typeof(Vector2<UInt64>),
            typeof(Vector2<sbyte>),
            typeof(Vector2<Int16>),
            typeof(Vector2<Int32>),
            typeof(Vector2<Int64>),
            typeof(Vector2<float>),
            typeof(Vector2<double>),
            typeof(Vector3<byte>),
            typeof(Vector3<UInt16>),
            typeof(Vector3<UInt32>),
            typeof(Vector3<UInt64>),
            typeof(Vector3<sbyte>),
            typeof(Vector3<Int16>),
            typeof(Vector3<Int32>),
            typeof(Vector3<Int64>),
            typeof(Vector3<float>),
            typeof(Vector3<double>),
            typeof(Vector4<byte>),
            typeof(Vector4<UInt16>),
            typeof(Vector4<UInt32>),
            typeof(Vector4<UInt64>),
            typeof(Vector4<sbyte>),
            typeof(Vector4<Int16>),
            typeof(Vector4<Int32>),
            typeof(Vector4<Int64>),
            typeof(Vector4<float>),
            typeof(Vector4<double>),
        };
    }
}
