using System.Text;

namespace Onyx.CodeGen.Core
{
    public class CodeGenerator
    {
        public class CodeScope : IDisposable
        {
            private CodeGenerator generator;
            private string scopeExitString = "}";

            public CodeScope(CodeGenerator generator)
            {
                this.generator = generator;
                generator.Append('{');
                ++generator.scope;
            }

            public CodeScope(CodeGenerator generator, string scopeEnterString, string scopeExitString)
            {
                this.generator = generator;
                this.scopeExitString = scopeExitString;

                if (string.IsNullOrEmpty(scopeEnterString) == false)
                    generator.Append(scopeEnterString);
                ++generator.scope;
            }

            public void Dispose()
            {
                --generator.scope;
                if (string.IsNullOrEmpty(scopeExitString) == false)
                    generator.Append(scopeExitString);
            }
        }

        public const string AUTO_GENERATED_FILE_HEADER = """
           //------------------------------------------------------------------------------
           // <auto-generated>
           //     This file was generated.
           //     Do not edit this file directly. Any changes will be overwritten
           //     with the next build.
           // </auto-generated>
           //------------------------------------------------------------------------------

           """;
        

        private int scope = 0;
        private StringBuilder stringBuilder;
        private int includesInsertIndex = 0;
        private HashSet<string> includes = new HashSet<string>();

        public CodeGenerator()
        {
            stringBuilder = new StringBuilder(AUTO_GENERATED_FILE_HEADER);
            includesInsertIndex = stringBuilder.Length;
        }

        public CodeGenerator(string str)
        {
            stringBuilder = new StringBuilder(str);
            includesInsertIndex = stringBuilder.Length;
        }

        public CodeScope EnterScope(string scopeName)
        {
            Append(scopeName);
            return new CodeScope(this);
        }

        public CodeScope EnterMultilineFunctionCall(string scopeName)
        {
            Append(scopeName);
            return new CodeScope(this, "(", ");");
        }

        public CodeScope EnterFunction(string scopeName)
        {
            Append(scopeName);
            return new CodeScope(this);
        }

        public CodeScope EnterScopeNoBraces()
        {
            return new CodeScope(this, "", "");
        }

        public CodeScope EnterClass(string scopeName)
        {
            Append(scopeName);
            return new CodeScope(this, "{", "};");
        }

        public CodeScope EnterScope()
        {
            return new CodeScope(this);
        }

        public void Insert(int index, string str)
        {
            stringBuilder.Insert(index ,$"{new string(' ', 4 * scope)}{str}\n");
        }

        public void AppendLine()
        {
            stringBuilder.AppendLine();
        }

        public void Append(char character)
        {
            stringBuilder.AppendLine($"{new string(' ', 4 * scope)}{character}");
        }

        public void Append(string str, bool skipIndent = false)
        {
            if (skipIndent)
            {
                stringBuilder.AppendLine(str);
            }
            else
            {
                stringBuilder.AppendLine($"{new string(' ', 4 * scope)}{str}");
            }
            
        }

        public void Append(IEnumerable<string> lines)
        {
            foreach (var line in lines)
            {
                Append(line);
            }
        }

        public void AddInclude(string includePath)
        {
            if (string.IsNullOrWhiteSpace(includePath))
                return;

            includes.Add(includePath);
        }

        public void AddIncludes(IEnumerable<string> includePaths)
        {
            foreach (var includePath in includePaths)
            {
                AddInclude(includePath);
            }
        }

        public string GetCode()
        {
            var code = stringBuilder.ToString();
            code = InsertIncludes(code);
            return code;
        }

        public IEnumerable<string> GetCodeLines()
        {
            return GetCode().Split(Environment.NewLine);
        }

        private string InsertIncludes(string code)
        {
            if (includes.Count == 0)
                return code;

            var lines = includes
                .OrderBy(s => s.Count(c => c == '/' || c == '\\'))
                .ThenBy(s => s)
                .Select(s => $"#include <{s}>")
                .Append(string.Empty); // blank line after includes

            var block = string.Join(Environment.NewLine, lines);
            return code.Insert(includesInsertIndex, block);
        }
    }
}
