using System.Text;

namespace Onyx.CodeGen.Core
{
    public class CodeGenerator
    {
        private class CodeScope : IDisposable
        {
            private Action OnDispose;

            public CodeScope()
            {
            }

            public CodeScope(Action onDispose)
            {
               this.OnDispose = onDispose;
            }

            public void Dispose()
            {
                if (OnDispose != null)
                    OnDispose();
            }
        }

        public const string AUTO_GENERATED_FILE_CPP_HEADER = """
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This file was generated.
            //     Do not edit this file directly. Any changes will be overwritten
            //     with the next build.
            // </auto-generated>
            //------------------------------------------------------------------------------

            """;

        public const string AUTO_GENERATED_FILE_H_HEADER = """
           //------------------------------------------------------------------------------
           // <auto-generated>
           //     This file was generated.
           //     Do not edit this file directly. Any changes will be overwritten
           //     with the next build.
           // </auto-generated>
           //------------------------------------------------------------------------------
           #pragma once

           """;


        private int scope = 0;
        private StringBuilder stringBuilder;
        private int includesInsertIndex = 0;
        private HashSet<string> includes = new HashSet<string>();

        public CodeGenerator()
        {
            stringBuilder = new StringBuilder(AUTO_GENERATED_FILE_CPP_HEADER);
            includesInsertIndex = stringBuilder.Length;
        }

        public CodeGenerator(string str)
        {
            stringBuilder = new StringBuilder(str);
            includesInsertIndex = stringBuilder.Length;
        }

        public IDisposable EnterScope()
        {
            Append("{");
            ++scope;
            return new CodeScope(() => { --scope; Append("}"); });
        }

        public IDisposable EnterScope(string scopeName)
        {
            Append(scopeName);
            Append("{");
            ++scope;
            return new CodeScope(() => { --scope; Append("}"); });
        }

        public IDisposable EnterScope(string scopeName, string scopeBegin, string scopeEnd)
        {
            Append(scopeName);
            Append(scopeBegin);
            ++scope;
            return new CodeScope(() => { --scope; Append(scopeEnd); });
        }

        public IDisposable EnterPreprocessorScope(string preprocessorCheck)
        {
            if (string.IsNullOrWhiteSpace(preprocessorCheck))
            {
                return new CodeScope();
            }
            else
            {
                Append($"#if {preprocessorCheck}", true);
                return new CodeScope(() => { Append($"#endif //{preprocessorCheck}", true); });
            }
        }

        public IDisposable EnterMultilineFunctionCall(string function)
        {
            return EnterScope(function, "(", ");");
        }

        public IDisposable Indent()
        {
            ++scope;
            return new CodeScope(() => { --scope; });
        }

        public IDisposable EnterClass(string className)
        {
            return EnterScope(className, "{", "};");
        }

        public void Insert(int index, string str)
        {
            stringBuilder.Insert(index ,$"{new string(' ', 4 * scope)}{str}\n");
        }

        public void AppendLine()
        {
            stringBuilder.AppendLine();
        }

        public void Append(char character)
        {
            stringBuilder.AppendLine($"{new string(' ', 4 * scope)}{character}");
        }

        public void Append(string str, bool skipIndent = false)
        {
            if (skipIndent)
            {
                stringBuilder.AppendLine(str);
            }
            else
            {
                stringBuilder.AppendLine($"{new string(' ', 4 * scope)}{str}");
            }
            
        }

        public void Append(IEnumerable<string> lines)
        {
            foreach (var line in lines)
            {
                Append(line);
            }
        }

        public void AddInclude(string includePath)
        {
            if (string.IsNullOrWhiteSpace(includePath))
                return;

            includes.Add(includePath);
        }

        public void AddIncludes(IEnumerable<string> includePaths)
        {
            foreach (var includePath in includePaths)
            {
                AddInclude(includePath);
            }
        }

        public string GetCode()
        {
            var code = stringBuilder.ToString();
            code = InsertIncludes(code);
            return code;
        }

        public IEnumerable<string> GetCodeLines()
        {
            var code = GetCode();
            if (string.IsNullOrWhiteSpace(code))
                return Enumerable.Empty<string>();
                
            return GetCode().Split(Environment.NewLine);
        }

        private string InsertIncludes(string code)
        {
            if (includes.Count == 0)
                return code;

            var lines = includes
                .OrderBy(s => s.Count(c => c == '/' || c == '\\'))
                .ThenBy(s => s)
                .Select(s => $"#include <{s}>")
                .Append(string.Empty); // blank line after includes

            var block = string.Join(Environment.NewLine, lines);
            return code.Insert(includesInsertIndex, block);
        }
    }
}
