using System.Text;

namespace onyx_codegen.common
{
    internal class CodeGenerator
    {
        internal const string AUTO_GENERATED_FILE_HEADER = """
           //------------------------------------------------------------------------------
           // <auto-generated>
           //     This file was generated.
           //     Do not edit this file directly. Any changes will be overwritten
           //     with the next build.
           // </auto-generated>
           //------------------------------------------------------------------------------

           """;

        internal struct CodeScope : IDisposable
        {
            private CodeGenerator generator;
            private string scopeExitString = "}";
            public CodeScope(CodeGenerator generator)
            {
                this.generator = generator;
                generator.Append('{');
                ++generator.scope;
            }

            public CodeScope(CodeGenerator generator, string scopeEnterString, string scopeExitString)
            {
                this.generator = generator;
                this.scopeExitString = scopeExitString;

                if ( string.IsNullOrEmpty(scopeEnterString) == false )
                    generator.Append(scopeEnterString);
                ++generator.scope;
            }

            public void Dispose()
            {
                --generator.scope;
                if (string.IsNullOrEmpty(scopeExitString) == false)
                    generator.Append(scopeExitString);
            }
        }

        private int scope = 0;
        private StringBuilder stringBuilder;

        internal CodeGenerator()
        {
            this.stringBuilder = new StringBuilder(AUTO_GENERATED_FILE_HEADER);
        }

        internal CodeGenerator(string str)
        {
            this.stringBuilder = new StringBuilder(str);
        }

        internal CodeScope EnterScope(string scopeName)
        {
            Append(scopeName);
            return new CodeScope(this);
        }

        internal CodeScope EnterMultilineFunctionCall(string scopeName)
        {
            Append(scopeName);
            return new CodeScope(this, "(", ");");
        }

        internal CodeScope EnterFunction(string scopeName)
        {
            Append(scopeName);
            return new CodeScope(this, "(", ")");
        }

        internal CodeScope EnterScopeNoBraces()
        {
            return new CodeScope(this, "", "");
        }

        internal CodeScope EnterClass(string scopeName)
        {
            Append(scopeName);
            return new CodeScope(this, "{", "};");
        }

        internal CodeScope EnterScope()
        {
            return new CodeScope(this);
        }

        internal void Insert(int index, string str)
        {
            stringBuilder.Insert(index ,$"{new string(' ', 4 * scope)}{str}\n");
        }

        internal void AppendLine()
        {
            stringBuilder.AppendLine();
        }

        internal void Append(char character)
        {
            stringBuilder.AppendLine($"{new string(' ', 4 * scope)}{character}");
        }

        internal void Append(string str)
        {
            stringBuilder.AppendLine($"{new string(' ', 4 * scope)}{str}");
        }

        internal void Append(IEnumerable<string> lines)
        {
            foreach (var line in lines)
            {
                Append(line);
            }
        }

        internal string GetCode()
        {
            return stringBuilder.ToString();
        }
    }
}
